# Generated by Django 5.2.14 on 2026-05-21 04:17

from django.db import migrations, models


def seed_project_statuses(apps, schema_editor):
    ProjectStatus = apps.get_model('crm_app', 'ProjectStatus')

    defaults = [
        {"code": "active", "name": "В работе", "short_name": "Работа", "color": "sky", "sort_order": 10, "is_default": True},
        {"code": "closed", "name": "Завершено", "short_name": "Готово", "color": "emerald", "sort_order": 20, "is_default": False},
        {"code": "canceled", "name": "Отменено", "short_name": "Стоп", "color": "rose", "sort_order": 30, "is_default": False},
    ]

    for item in defaults:
        ProjectStatus.objects.update_or_create(code=item["code"], defaults=item)


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_projectcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(allow_unicode=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, default='', max_length=40)),
                ('color', models.CharField(choices=[('sky', 'Sky'), ('emerald', 'Emerald'), ('rose', 'Rose'), ('amber', 'Amber'), ('violet', 'Violet'), ('slate', 'Slate')], default='sky', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=50),
        ),
        migrations.RunPython(seed_project_statuses, migrations.RunPython.noop),
    ]
