# Generated by Django 5.2.14 on 2026-06-07 06:52

from django.db import migrations, models


def seed_project_creation_count(apps, _schema_editor):
    Project = apps.get_model("crm_app", "Project")
    WorkspaceSubscription = apps.get_model("crm_app", "WorkspaceSubscription")
    project_count = Project.objects.count()
    for subscription in WorkspaceSubscription.objects.all():
        subscription.project_creations_count = max(subscription.project_creations_count, project_count)
        subscription.save(update_fields=["project_creations_count"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_payment_account_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_assistant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='project_creations_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_project_creation_count, migrations.RunPython.noop),
    ]
