# Generated by Django 5.2.14 on 2026-06-09 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_project_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('chatwoot', 'Chatwoot')], default='chatwoot', max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('base_url', models.URLField(blank=True, default='')),
                ('account_id', models.CharField(blank=True, default='', max_length=60)),
                ('inbox_name', models.CharField(blank=True, default='', max_length=120)),
                ('api_access_token', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_chat_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat integration settings',
                'verbose_name_plural': 'Chat integration settings',
            },
        ),
    ]
