# Generated by Django 5.2.14 on 2026-06-09 09:35

import django.db.models.deletion
from django.db import migrations, models


def assign_default_workspace(apps, _schema_editor):
    Workspace = apps.get_model('crm_app', 'Workspace')
    workspace, _created = Workspace.objects.get_or_create(
        slug='default',
        defaults={'name': 'Основная компания'},
    )

    for model_name in [
        'Account',
        'AuditLog',
        'Client',
        'DocumentTemplate',
        'FinanceCategory',
        'Project',
        'ProjectCustomField',
        'ProjectStatus',
        'User',
    ]:
        model = apps.get_model('crm_app', model_name)
        model.objects.filter(workspace__isnull=True).update(workspace=workspace)

    ChatIntegrationSettings = apps.get_model('crm_app', 'ChatIntegrationSettings')
    chat_settings = ChatIntegrationSettings.objects.filter(workspace__isnull=True).order_by('id')
    if chat_settings.exists():
        first = chat_settings.first()
        first.workspace = workspace
        first.save(update_fields=['workspace'])

    WorkspaceSubscription = apps.get_model('crm_app', 'WorkspaceSubscription')
    subscriptions = WorkspaceSubscription.objects.filter(workspace__isnull=True).order_by('id')
    if subscriptions.exists():
        first = subscriptions.first()
        first.workspace = workspace
        first.save(update_fields=['workspace'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_chatintegrationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_phone_non_empty',
        ),
        migrations.RemoveConstraint(
            model_name='financecategory',
            name='unique_finance_category_name_type',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='type',
            field=models.CharField(choices=[('contract', 'Contract'), ('act', 'Act')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='code',
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AddField(
            model_name='account',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='chatintegrationsettings',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='client',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='financecategory',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_categories', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='projectcustomfield',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_custom_fields', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_statuses', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='crm_app.workspace'),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='crm_app.workspace'),
        ),
        migrations.RunPython(assign_default_workspace, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_account_name'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('workspace', 'phone'), name='unique_workspace_client_phone_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'type'), name='unique_workspace_document_template_type'),
        ),
        migrations.AddConstraint(
            model_name='financecategory',
            constraint=models.UniqueConstraint(fields=('workspace', 'name', 'type'), name='unique_workspace_finance_category_name_type'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('workspace', 'order_number'), name='unique_workspace_project_order_number'),
        ),
        migrations.AddConstraint(
            model_name='projectstatus',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='unique_workspace_project_status_code'),
        ),
    ]
