# Generated by Django 5.2.14 on 2026-06-25 06:14

import crm_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='yandex_disk_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='yandex_disk_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='yandex_disk_path',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='project',
            name='yandex_disk_web_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='YandexDiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('auto_create_project_folders', models.BooleanField(default=True)),
                ('base_path', models.CharField(blank=True, default='/CRM/Проекты', max_length=500)),
                ('folder_template', models.JSONField(blank=True, default=crm_app.models.default_yandex_disk_folder_template)),
                ('oauth_token', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_yandex_disk_settings', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yandex_disk_settings', to='crm_app.workspace')),
            ],
            options={
                'verbose_name': 'Yandex Disk settings',
                'verbose_name_plural': 'Yandex Disk settings',
            },
        ),
    ]
