# Generated by Django 5.2.14 on 2026-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_project_yandex_disk_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='yandex_disk_archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yandexdisksettings',
            name='archive_path',
            field=models.CharField(blank=True, default='/CRM/Архив', max_length=500),
        ),
    ]
