# Generated by Django 5.2.14 on 2026-07-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0030_client_address_lat_client_address_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='includes_assistant',
        ),
        migrations.DeleteModel(
            name='CRMMemorySnapshot',
        ),
    ]
