# Generated by Django 5.2.14 on 2026-07-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0031_remove_assistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacesubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='workspacesubscription',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='SubscriptionInvoice',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='WorkspaceSubscription',
        ),
    ]
