# Generated by Django 5.2.14 on 2026-08-08 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0032_remove_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(max_length=64)),
                ('number', models.CharField(blank=True, default='', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('quote_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calculator_quotes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_calculator_quotes', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_quotes', to='crm_app.workspace')),
            ],
            options={
                'ordering': ['-quote_created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'quote_id'), name='unique_workspace_calculator_quote_id')],
            },
        ),
    ]
